### ISSUE TITLE
Devices 

### ISSUE THREAD

**Issue by alvnfaiz** [owodev/kecerahan#1]
devices yang dimaksud contohnya kayak apa?, apakah untuk semua perangkat android, dan desktop?

**Comment by ghost** [comment]
untuk saat ini hanya support Linux dan *BSD..
device yang dimaksud disini itu VGA..
kalo kamu pake linux silahkan cek menggunakan perintah
```console
$ ls /sys/class/backlight/
```
sebagai contoh, saya menggunakan amd radeon, maka result-nya
```console
$ ls /sys/class/backlight/
radeon_bl0@
```
kalo intel biasanya
```console
$ ls /sys/class/backlight/
intel_backlight@
````

**Comment by ghost** [comment]
kadang juga ada yang 2 resultnya

**Comment by ghost** [comment]
ok saya close
